"""Initial migration table

Revision ID: 156c2d5df954
Revises: 
Create Date: 2021-12-16 19:03:55.199527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '156c2d5df954'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barang',
    sa.Column('id_barang', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nama_barang', sa.String(length=30), nullable=True),
    sa.Column('harga', sa.Float(), nullable=True),
    sa.Column('id_suplier', sa.Integer(), nullable=True),
    sa.Column('keterangan', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id_barang')
    )
    op.create_table('pembelian',
    sa.Column('id_pembelian', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_barang', sa.Integer(), nullable=True),
    sa.Column('tanggal', sa.DateTime(), nullable=True),
    sa.Column('keterangan', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id_pembelian')
    )
    op.create_table('suplier',
    sa.Column('id_suplier', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nama_suplier', sa.String(length=30), nullable=True),
    sa.Column('no_telp', sa.String(length=15), nullable=True),
    sa.Column('alamat', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_suplier')
    )
    op.create_table('user',
    sa.Column('id_user', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nama', sa.String(length=25), nullable=True),
    sa.Column('username', sa.String(length=25), nullable=True),
    sa.Column('password', sa.String(length=25), nullable=True),
    sa.Column('email', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id_user')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('suplier')
    op.drop_table('pembelian')
    op.drop_table('barang')
    # ### end Alembic commands ###
