"""barang

Revision ID: 16ce1cf188e5
Revises: 1875d1bc2ea1
Create Date: 2021-12-19 21:05:29.765448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16ce1cf188e5'
down_revision = '1875d1bc2ea1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'barang', 'suplier', ['id_suplier'], ['id_suplier'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'barang', type_='foreignkey')
    # ### end Alembic commands ###
