"""Initial migration foreign

Revision ID: 1875d1bc2ea1
Revises: 7d3edbb230f8
Create Date: 2021-12-19 20:22:17.207711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1875d1bc2ea1'
down_revision = '7d3edbb230f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pembelian', sa.Column('id_user', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pembelian', 'user', ['id_user'], ['id_user'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pembelian', type_='foreignkey')
    op.drop_column('pembelian', 'id_user')
    # ### end Alembic commands ###
