"""Initial migration status

Revision ID: 2f483bbe7419
Revises: 156c2d5df954
Create Date: 2021-12-19 19:08:40.045576

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2f483bbe7419'
down_revision = '156c2d5df954'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('barang', sa.Column('status', sa.String(length=10), nullable=True))
    op.drop_column('barang', 'keterangan')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('barang', sa.Column('keterangan', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('barang', 'status')
    # ### end Alembic commands ###
