"""Initial migration pembelian

Revision ID: 5f59a9bf6770
Revises: 8d0ce981977b
Create Date: 2021-12-15 17:24:16.990935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f59a9bf6770'
down_revision = '8d0ce981977b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pembelian',
    sa.Column('id_pembelian', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_barang', sa.Integer(), nullable=True),
    sa.Column('tanggal', sa.DateTime(), nullable=True),
    sa.Column('keterangan', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id_pembelian')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pembelian')
    # ### end Alembic commands ###
