"""Initial migration pembelian

Revision ID: 7d3edbb230f8
Revises: 2f483bbe7419
Create Date: 2021-12-19 20:20:06.616784

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7d3edbb230f8'
down_revision = '2f483bbe7419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pembelian', 'id_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pembelian', sa.Column('id_user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
