"""Initial migration 1

Revision ID: 8d0ce981977b
Revises: f6d1b4085244
Create Date: 2021-12-15 16:34:34.926873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d0ce981977b'
down_revision = 'f6d1b4085244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suplier',
    sa.Column('id_suplier', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nama_suplier', sa.String(length=30), nullable=True),
    sa.Column('no_telp', sa.String(length=15), nullable=True),
    sa.Column('alamat', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_suplier')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suplier')
    # ### end Alembic commands ###
