"""'pembelian'

Revision ID: da17047de5fa
Revises: da66374f23f8
Create Date: 2021-12-20 09:16:47.011580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da17047de5fa'
down_revision = 'da66374f23f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'pembelian', 'barang', ['id_barang'], ['id_barang'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pembelian', type_='foreignkey')
    # ### end Alembic commands ###
