"""Initial migration.

Revision ID: f6d1b4085244
Revises: 
Create Date: 2021-12-15 16:33:51.657853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6d1b4085244'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barang',
    sa.Column('id_barang', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nama_barang', sa.String(length=30), nullable=True),
    sa.Column('harga', sa.Float(), nullable=True),
    sa.Column('id_suplier', sa.Integer(), nullable=True),
    sa.Column('keterangan', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id_barang')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('barang')
    # ### end Alembic commands ###
